// Code generated by mockery v2.53.6. DO NOT EDIT.

package servicemocks

import (
	context "context"

	client "go.lumeweb.com/ipfs-sdk/internal/client"

	http "go.lumeweb.com/ipfs-sdk/internal/http"

	mock "github.com/stretchr/testify/mock"
)

// MockWebsitesService is an autogenerated mock type for the WebsitesService type
type MockWebsitesService struct {
	mock.Mock
}

type MockWebsitesService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebsitesService) EXPECT() *MockWebsitesService_Expecter {
	return &MockWebsitesService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, domain, targetHash, targetType
func (_m *MockWebsitesService) Create(ctx context.Context, domain string, targetHash string, targetType string) (*client.WebsiteResponse, error) {
	ret := _m.Called(ctx, domain, targetHash, targetType)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *client.WebsiteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*client.WebsiteResponse, error)); ok {
		return rf(ctx, domain, targetHash, targetType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *client.WebsiteResponse); ok {
		r0 = rf(ctx, domain, targetHash, targetType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.WebsiteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, domain, targetHash, targetType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWebsitesService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - targetHash string
//   - targetType string
func (_e *MockWebsitesService_Expecter) Create(ctx interface{}, domain interface{}, targetHash interface{}, targetType interface{}) *MockWebsitesService_Create_Call {
	return &MockWebsitesService_Create_Call{Call: _e.mock.On("Create", ctx, domain, targetHash, targetType)}
}

func (_c *MockWebsitesService_Create_Call) Run(run func(ctx context.Context, domain string, targetHash string, targetType string)) *MockWebsitesService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockWebsitesService_Create_Call) Return(_a0 *client.WebsiteResponse, _a1 error) *MockWebsitesService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesService_Create_Call) RunAndReturn(run func(context.Context, string, string, string) (*client.WebsiteResponse, error)) *MockWebsitesService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithOptions provides a mock function with given fields: ctx, req
func (_m *MockWebsitesService) CreateWithOptions(ctx context.Context, req client.WebsiteRequest) (*client.WebsiteResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithOptions")
	}

	var r0 *client.WebsiteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.WebsiteRequest) (*client.WebsiteResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.WebsiteRequest) *client.WebsiteResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.WebsiteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.WebsiteRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesService_CreateWithOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithOptions'
type MockWebsitesService_CreateWithOptions_Call struct {
	*mock.Call
}

// CreateWithOptions is a helper method to define mock.On call
//   - ctx context.Context
//   - req client.WebsiteRequest
func (_e *MockWebsitesService_Expecter) CreateWithOptions(ctx interface{}, req interface{}) *MockWebsitesService_CreateWithOptions_Call {
	return &MockWebsitesService_CreateWithOptions_Call{Call: _e.mock.On("CreateWithOptions", ctx, req)}
}

func (_c *MockWebsitesService_CreateWithOptions_Call) Run(run func(ctx context.Context, req client.WebsiteRequest)) *MockWebsitesService_CreateWithOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.WebsiteRequest))
	})
	return _c
}

func (_c *MockWebsitesService_CreateWithOptions_Call) Return(_a0 *client.WebsiteResponse, _a1 error) *MockWebsitesService_CreateWithOptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesService_CreateWithOptions_Call) RunAndReturn(run func(context.Context, client.WebsiteRequest) (*client.WebsiteResponse, error)) *MockWebsitesService_CreateWithOptions_Call {
	_c.Call.Return(run)
	return _c
}

// CreateHNSDomain provides a mock function with given fields: ctx, id, domain
func (_m *MockWebsitesService) CreateHNSDomain(ctx context.Context, id string, domain string) (*client.HNSDomainResponse, error) {
	ret := _m.Called(ctx, id, domain)

	if len(ret) == 0 {
		panic("no return value specified for CreateHNSDomain")
	}

	var r0 *client.HNSDomainResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*client.HNSDomainResponse, error)); ok {
		return rf(ctx, id, domain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *client.HNSDomainResponse); ok {
		r0 = rf(ctx, id, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.HNSDomainResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesService_CreateHNSDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateHNSDomain'
type MockWebsitesService_CreateHNSDomain_Call struct {
	*mock.Call
}

// CreateHNSDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - domain string
func (_e *MockWebsitesService_Expecter) CreateHNSDomain(ctx interface{}, id interface{}, domain interface{}) *MockWebsitesService_CreateHNSDomain_Call {
	return &MockWebsitesService_CreateHNSDomain_Call{Call: _e.mock.On("CreateHNSDomain", ctx, id, domain)}
}

func (_c *MockWebsitesService_CreateHNSDomain_Call) Run(run func(ctx context.Context, id string, domain string)) *MockWebsitesService_CreateHNSDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockWebsitesService_CreateHNSDomain_Call) Return(_a0 *client.HNSDomainResponse, _a1 error) *MockWebsitesService_CreateHNSDomain_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesService_CreateHNSDomain_Call) RunAndReturn(run func(context.Context, string, string) (*client.HNSDomainResponse, error)) *MockWebsitesService_CreateHNSDomain_Call {
	_c.Call.Return(run)
	return _c
}

// CreateHNSDomainWithOptions provides a mock function with given fields: ctx, id, req
func (_m *MockWebsitesService) CreateHNSDomainWithOptions(ctx context.Context, id string, req client.HNSDomainRequest) (*client.HNSDomainResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateHNSDomainWithOptions")
	}

	var r0 *client.HNSDomainResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.HNSDomainRequest) (*client.HNSDomainResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.HNSDomainRequest) *client.HNSDomainResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.HNSDomainResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.HNSDomainRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesService_CreateHNSDomainWithOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateHNSDomainWithOptions'
type MockWebsitesService_CreateHNSDomainWithOptions_Call struct {
	*mock.Call
}

// CreateHNSDomainWithOptions is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req client.HNSDomainRequest
func (_e *MockWebsitesService_Expecter) CreateHNSDomainWithOptions(ctx interface{}, id interface{}, req interface{}) *MockWebsitesService_CreateHNSDomainWithOptions_Call {
	return &MockWebsitesService_CreateHNSDomainWithOptions_Call{Call: _e.mock.On("CreateHNSDomainWithOptions", ctx, id, req)}
}

func (_c *MockWebsitesService_CreateHNSDomainWithOptions_Call) Run(run func(ctx context.Context, id string, req client.HNSDomainRequest)) *MockWebsitesService_CreateHNSDomainWithOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(client.HNSDomainRequest))
	})
	return _c
}

func (_c *MockWebsitesService_CreateHNSDomainWithOptions_Call) Return(_a0 *client.HNSDomainResponse, _a1 error) *MockWebsitesService_CreateHNSDomainWithOptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesService_CreateHNSDomainWithOptions_Call) RunAndReturn(run func(context.Context, string, client.HNSDomainRequest) (*client.HNSDomainResponse, error)) *MockWebsitesService_CreateHNSDomainWithOptions_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockWebsitesService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebsitesService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWebsitesService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockWebsitesService_Expecter) Delete(ctx interface{}, id interface{}) *MockWebsitesService_Delete_Call {
	return &MockWebsitesService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockWebsitesService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockWebsitesService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWebsitesService_Delete_Call) Return(_a0 error) *MockWebsitesService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebsitesService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockWebsitesService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockWebsitesService) Get(ctx context.Context, id string) (*client.WebsiteResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *client.WebsiteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.WebsiteResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.WebsiteResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.WebsiteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWebsitesService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockWebsitesService_Expecter) Get(ctx interface{}, id interface{}) *MockWebsitesService_Get_Call {
	return &MockWebsitesService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockWebsitesService_Get_Call) Run(run func(ctx context.Context, id string)) *MockWebsitesService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWebsitesService_Get_Call) Return(_a0 *client.WebsiteResponse, _a1 error) *MockWebsitesService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesService_Get_Call) RunAndReturn(run func(context.Context, string) (*client.WebsiteResponse, error)) *MockWebsitesService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function with given fields: ctx
func (_m *MockWebsitesService) GetConfig(ctx context.Context) (*client.WebsiteConfigResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 *client.WebsiteConfigResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*client.WebsiteConfigResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *client.WebsiteConfigResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.WebsiteConfigResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesService_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockWebsitesService_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWebsitesService_Expecter) GetConfig(ctx interface{}) *MockWebsitesService_GetConfig_Call {
	return &MockWebsitesService_GetConfig_Call{Call: _e.mock.On("GetConfig", ctx)}
}

func (_c *MockWebsitesService_GetConfig_Call) Run(run func(ctx context.Context)) *MockWebsitesService_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockWebsitesService_GetConfig_Call) Return(_a0 *client.WebsiteConfigResponse, _a1 error) *MockWebsitesService_GetConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesService_GetConfig_Call) RunAndReturn(run func(context.Context) (*client.WebsiteConfigResponse, error)) *MockWebsitesService_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetGatewayWebsite provides a mock function with given fields: ctx, domain
func (_m *MockWebsitesService) GetGatewayWebsite(ctx context.Context, domain string) (*client.GatewayWebsiteResponse, error) {
	ret := _m.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetGatewayWebsite")
	}

	var r0 *client.GatewayWebsiteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.GatewayWebsiteResponse, error)); ok {
		return rf(ctx, domain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.GatewayWebsiteResponse); ok {
		r0 = rf(ctx, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GatewayWebsiteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesService_GetGatewayWebsite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGatewayWebsite'
type MockWebsitesService_GetGatewayWebsite_Call struct {
	*mock.Call
}

// GetGatewayWebsite is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockWebsitesService_Expecter) GetGatewayWebsite(ctx interface{}, domain interface{}) *MockWebsitesService_GetGatewayWebsite_Call {
	return &MockWebsitesService_GetGatewayWebsite_Call{Call: _e.mock.On("GetGatewayWebsite", ctx, domain)}
}

func (_c *MockWebsitesService_GetGatewayWebsite_Call) Run(run func(ctx context.Context, domain string)) *MockWebsitesService_GetGatewayWebsite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWebsitesService_GetGatewayWebsite_Call) Return(_a0 *client.GatewayWebsiteResponse, _a1 error) *MockWebsitesService_GetGatewayWebsite_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesService_GetGatewayWebsite_Call) RunAndReturn(run func(context.Context, string) (*client.GatewayWebsiteResponse, error)) *MockWebsitesService_GetGatewayWebsite_Call {
	_c.Call.Return(run)
	return _c
}

// GetGatewayWebsiteStatus provides a mock function with given fields: ctx, domain
func (_m *MockWebsitesService) GetGatewayWebsiteStatus(ctx context.Context, domain string) (*client.GatewayWebsiteStatusResponse, error) {
	ret := _m.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetGatewayWebsiteStatus")
	}

	var r0 *client.GatewayWebsiteStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.GatewayWebsiteStatusResponse, error)); ok {
		return rf(ctx, domain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.GatewayWebsiteStatusResponse); ok {
		r0 = rf(ctx, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GatewayWebsiteStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesService_GetGatewayWebsiteStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGatewayWebsiteStatus'
type MockWebsitesService_GetGatewayWebsiteStatus_Call struct {
	*mock.Call
}

// GetGatewayWebsiteStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockWebsitesService_Expecter) GetGatewayWebsiteStatus(ctx interface{}, domain interface{}) *MockWebsitesService_GetGatewayWebsiteStatus_Call {
	return &MockWebsitesService_GetGatewayWebsiteStatus_Call{Call: _e.mock.On("GetGatewayWebsiteStatus", ctx, domain)}
}

func (_c *MockWebsitesService_GetGatewayWebsiteStatus_Call) Run(run func(ctx context.Context, domain string)) *MockWebsitesService_GetGatewayWebsiteStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWebsitesService_GetGatewayWebsiteStatus_Call) Return(_a0 *client.GatewayWebsiteStatusResponse, _a1 error) *MockWebsitesService_GetGatewayWebsiteStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesService_GetGatewayWebsiteStatus_Call) RunAndReturn(run func(context.Context, string) (*client.GatewayWebsiteStatusResponse, error)) *MockWebsitesService_GetGatewayWebsiteStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetSSLStatus provides a mock function with given fields: ctx, domain
func (_m *MockWebsitesService) GetSSLStatus(ctx context.Context, domain string) (*client.WebsiteResponse, error) {
	ret := _m.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetSSLStatus")
	}

	var r0 *client.WebsiteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.WebsiteResponse, error)); ok {
		return rf(ctx, domain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.WebsiteResponse); ok {
		r0 = rf(ctx, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.WebsiteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesService_GetSSLStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSSLStatus'
type MockWebsitesService_GetSSLStatus_Call struct {
	*mock.Call
}

// GetSSLStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockWebsitesService_Expecter) GetSSLStatus(ctx interface{}, domain interface{}) *MockWebsitesService_GetSSLStatus_Call {
	return &MockWebsitesService_GetSSLStatus_Call{Call: _e.mock.On("GetSSLStatus", ctx, domain)}
}

func (_c *MockWebsitesService_GetSSLStatus_Call) Run(run func(ctx context.Context, domain string)) *MockWebsitesService_GetSSLStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWebsitesService_GetSSLStatus_Call) Return(_a0 *client.WebsiteResponse, _a1 error) *MockWebsitesService_GetSSLStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesService_GetSSLStatus_Call) RunAndReturn(run func(context.Context, string) (*client.WebsiteResponse, error)) *MockWebsitesService_GetSSLStatus_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockWebsitesService) List(ctx context.Context) ([]client.WebsiteItem, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []client.WebsiteItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.WebsiteItem, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.WebsiteItem); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.WebsiteItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWebsitesService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWebsitesService_Expecter) List(ctx interface{}) *MockWebsitesService_List_Call {
	return &MockWebsitesService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockWebsitesService_List_Call) Run(run func(ctx context.Context)) *MockWebsitesService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockWebsitesService_List_Call) Return(_a0 []client.WebsiteItem, _a1 error) *MockWebsitesService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesService_List_Call) RunAndReturn(run func(context.Context) ([]client.WebsiteItem, error)) *MockWebsitesService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListHNSDomains provides a mock function with given fields: ctx, id
func (_m *MockWebsitesService) ListHNSDomains(ctx context.Context, id string) ([]client.HNSDomainItem, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ListHNSDomains")
	}

	var r0 []client.HNSDomainItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]client.HNSDomainItem, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []client.HNSDomainItem); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.HNSDomainItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesService_ListHNSDomains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHNSDomains'
type MockWebsitesService_ListHNSDomains_Call struct {
	*mock.Call
}

// ListHNSDomains is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockWebsitesService_Expecter) ListHNSDomains(ctx interface{}, id interface{}) *MockWebsitesService_ListHNSDomains_Call {
	return &MockWebsitesService_ListHNSDomains_Call{Call: _e.mock.On("ListHNSDomains", ctx, id)}
}

func (_c *MockWebsitesService_ListHNSDomains_Call) Run(run func(ctx context.Context, id string)) *MockWebsitesService_ListHNSDomains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWebsitesService_ListHNSDomains_Call) Return(_a0 []client.HNSDomainItem, _a1 error) *MockWebsitesService_ListHNSDomains_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesService_ListHNSDomains_Call) RunAndReturn(run func(context.Context, string) ([]client.HNSDomainItem, error)) *MockWebsitesService_ListHNSDomains_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, domain, targetHash, targetType
func (_m *MockWebsitesService) Update(ctx context.Context, id string, domain string, targetHash string, targetType string) (*client.WebsiteResponse, error) {
	ret := _m.Called(ctx, id, domain, targetHash, targetType)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *client.WebsiteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*client.WebsiteResponse, error)); ok {
		return rf(ctx, id, domain, targetHash, targetType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *client.WebsiteResponse); ok {
		r0 = rf(ctx, id, domain, targetHash, targetType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.WebsiteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, id, domain, targetHash, targetType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockWebsitesService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - domain string
//   - targetHash string
//   - targetType string
func (_e *MockWebsitesService_Expecter) Update(ctx interface{}, id interface{}, domain interface{}, targetHash interface{}, targetType interface{}) *MockWebsitesService_Update_Call {
	return &MockWebsitesService_Update_Call{Call: _e.mock.On("Update", ctx, id, domain, targetHash, targetType)}
}

func (_c *MockWebsitesService_Update_Call) Run(run func(ctx context.Context, id string, domain string, targetHash string, targetType string)) *MockWebsitesService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockWebsitesService_Update_Call) Return(_a0 *client.WebsiteResponse, _a1 error) *MockWebsitesService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesService_Update_Call) RunAndReturn(run func(context.Context, string, string, string, string) (*client.WebsiteResponse, error)) *MockWebsitesService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSSLStatusInternal provides a mock function with given fields: ctx, domain, sslStatus
func (_m *MockWebsitesService) UpdateSSLStatusInternal(ctx context.Context, domain string, sslStatus client.SSLStatusUpdateRequest) error {
	ret := _m.Called(ctx, domain, sslStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSSLStatusInternal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.SSLStatusUpdateRequest) error); ok {
		r0 = rf(ctx, domain, sslStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebsitesService_UpdateSSLStatusInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSSLStatusInternal'
type MockWebsitesService_UpdateSSLStatusInternal_Call struct {
	*mock.Call
}

// UpdateSSLStatusInternal is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - sslStatus client.SSLStatusUpdateRequest
func (_e *MockWebsitesService_Expecter) UpdateSSLStatusInternal(ctx interface{}, domain interface{}, sslStatus interface{}) *MockWebsitesService_UpdateSSLStatusInternal_Call {
	return &MockWebsitesService_UpdateSSLStatusInternal_Call{Call: _e.mock.On("UpdateSSLStatusInternal", ctx, domain, sslStatus)}
}

func (_c *MockWebsitesService_UpdateSSLStatusInternal_Call) Run(run func(ctx context.Context, domain string, sslStatus client.SSLStatusUpdateRequest)) *MockWebsitesService_UpdateSSLStatusInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(client.SSLStatusUpdateRequest))
	})
	return _c
}

func (_c *MockWebsitesService_UpdateSSLStatusInternal_Call) Return(_a0 error) *MockWebsitesService_UpdateSSLStatusInternal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebsitesService_UpdateSSLStatusInternal_Call) RunAndReturn(run func(context.Context, string, client.SSLStatusUpdateRequest) error) *MockWebsitesService_UpdateSSLStatusInternal_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithOptions provides a mock function with given fields: ctx, id, req
func (_m *MockWebsitesService) UpdateWithOptions(ctx context.Context, id string, req client.WebsiteUpdateRequest) (*client.WebsiteResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithOptions")
	}

	var r0 *client.WebsiteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.WebsiteUpdateRequest) (*client.WebsiteResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.WebsiteUpdateRequest) *client.WebsiteResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.WebsiteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.WebsiteUpdateRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesService_UpdateWithOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithOptions'
type MockWebsitesService_UpdateWithOptions_Call struct {
	*mock.Call
}

// UpdateWithOptions is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req client.WebsiteUpdateRequest
func (_e *MockWebsitesService_Expecter) UpdateWithOptions(ctx interface{}, id interface{}, req interface{}) *MockWebsitesService_UpdateWithOptions_Call {
	return &MockWebsitesService_UpdateWithOptions_Call{Call: _e.mock.On("UpdateWithOptions", ctx, id, req)}
}

func (_c *MockWebsitesService_UpdateWithOptions_Call) Run(run func(ctx context.Context, id string, req client.WebsiteUpdateRequest)) *MockWebsitesService_UpdateWithOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(client.WebsiteUpdateRequest))
	})
	return _c
}

func (_c *MockWebsitesService_UpdateWithOptions_Call) Return(_a0 *client.WebsiteResponse, _a1 error) *MockWebsitesService_UpdateWithOptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesService_UpdateWithOptions_Call) RunAndReturn(run func(context.Context, string, client.WebsiteUpdateRequest) (*client.WebsiteResponse, error)) *MockWebsitesService_UpdateWithOptions_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateDNS provides a mock function with given fields: ctx, id
func (_m *MockWebsitesService) ValidateDNS(ctx context.Context, id string) (*client.WebsiteValidateResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ValidateDNS")
	}

	var r0 *client.WebsiteValidateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.WebsiteValidateResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.WebsiteValidateResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.WebsiteValidateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesService_ValidateDNS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateDNS'
type MockWebsitesService_ValidateDNS_Call struct {
	*mock.Call
}

// ValidateDNS is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockWebsitesService_Expecter) ValidateDNS(ctx interface{}, id interface{}) *MockWebsitesService_ValidateDNS_Call {
	return &MockWebsitesService_ValidateDNS_Call{Call: _e.mock.On("ValidateDNS", ctx, id)}
}

func (_c *MockWebsitesService_ValidateDNS_Call) Run(run func(ctx context.Context, id string)) *MockWebsitesService_ValidateDNS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWebsitesService_ValidateDNS_Call) Return(_a0 *client.WebsiteValidateResponse, _a1 error) *MockWebsitesService_ValidateDNS_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesService_ValidateDNS_Call) RunAndReturn(run func(context.Context, string) (*client.WebsiteValidateResponse, error)) *MockWebsitesService_ValidateDNS_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForDNSValidation provides a mock function with given fields: ctx, id, opts
func (_m *MockWebsitesService) WaitForDNSValidation(ctx context.Context, id string, opts ...http.PollOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WaitForDNSValidation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.PollOption) error); ok {
		r0 = rf(ctx, id, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebsitesService_WaitForDNSValidation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForDNSValidation'
type MockWebsitesService_WaitForDNSValidation_Call struct {
	*mock.Call
}

// WaitForDNSValidation is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - opts ...http.PollOption
func (_e *MockWebsitesService_Expecter) WaitForDNSValidation(ctx interface{}, id interface{}, opts ...interface{}) *MockWebsitesService_WaitForDNSValidation_Call {
	return &MockWebsitesService_WaitForDNSValidation_Call{Call: _e.mock.On("WaitForDNSValidation",
		append([]interface{}{ctx, id}, opts...)...)}
}

func (_c *MockWebsitesService_WaitForDNSValidation_Call) Run(run func(ctx context.Context, id string, opts ...http.PollOption)) *MockWebsitesService_WaitForDNSValidation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.PollOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.PollOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesService_WaitForDNSValidation_Call) Return(_a0 error) *MockWebsitesService_WaitForDNSValidation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebsitesService_WaitForDNSValidation_Call) RunAndReturn(run func(context.Context, string, ...http.PollOption) error) *MockWebsitesService_WaitForDNSValidation_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForSSLStatusReady provides a mock function with given fields: ctx, domain, opts
func (_m *MockWebsitesService) WaitForSSLStatusReady(ctx context.Context, domain string, opts ...http.PollOption) (string, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, domain)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WaitForSSLStatusReady")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.PollOption) (string, error)); ok {
		return rf(ctx, domain, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.PollOption) string); ok {
		r0 = rf(ctx, domain, opts...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...http.PollOption) error); ok {
		r1 = rf(ctx, domain, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesService_WaitForSSLStatusReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForSSLStatusReady'
type MockWebsitesService_WaitForSSLStatusReady_Call struct {
	*mock.Call
}

// WaitForSSLStatusReady is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - opts ...http.PollOption
func (_e *MockWebsitesService_Expecter) WaitForSSLStatusReady(ctx interface{}, domain interface{}, opts ...interface{}) *MockWebsitesService_WaitForSSLStatusReady_Call {
	return &MockWebsitesService_WaitForSSLStatusReady_Call{Call: _e.mock.On("WaitForSSLStatusReady",
		append([]interface{}{ctx, domain}, opts...)...)}
}

func (_c *MockWebsitesService_WaitForSSLStatusReady_Call) Run(run func(ctx context.Context, domain string, opts ...http.PollOption)) *MockWebsitesService_WaitForSSLStatusReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.PollOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.PollOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesService_WaitForSSLStatusReady_Call) Return(_a0 string, _a1 error) *MockWebsitesService_WaitForSSLStatusReady_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesService_WaitForSSLStatusReady_Call) RunAndReturn(run func(context.Context, string, ...http.PollOption) (string, error)) *MockWebsitesService_WaitForSSLStatusReady_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForWebsiteStatus provides a mock function with given fields: ctx, id, expectedStatus, opts
func (_m *MockWebsitesService) WaitForWebsiteStatus(ctx context.Context, id string, expectedStatus string, opts ...http.PollOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id, expectedStatus)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WaitForWebsiteStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...http.PollOption) error); ok {
		r0 = rf(ctx, id, expectedStatus, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebsitesService_WaitForWebsiteStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForWebsiteStatus'
type MockWebsitesService_WaitForWebsiteStatus_Call struct {
	*mock.Call
}

// WaitForWebsiteStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - expectedStatus string
//   - opts ...http.PollOption
func (_e *MockWebsitesService_Expecter) WaitForWebsiteStatus(ctx interface{}, id interface{}, expectedStatus interface{}, opts ...interface{}) *MockWebsitesService_WaitForWebsiteStatus_Call {
	return &MockWebsitesService_WaitForWebsiteStatus_Call{Call: _e.mock.On("WaitForWebsiteStatus",
		append([]interface{}{ctx, id, expectedStatus}, opts...)...)}
}

func (_c *MockWebsitesService_WaitForWebsiteStatus_Call) Run(run func(ctx context.Context, id string, expectedStatus string, opts ...http.PollOption)) *MockWebsitesService_WaitForWebsiteStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.PollOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.PollOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesService_WaitForWebsiteStatus_Call) Return(_a0 error) *MockWebsitesService_WaitForWebsiteStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebsitesService_WaitForWebsiteStatus_Call) RunAndReturn(run func(context.Context, string, string, ...http.PollOption) error) *MockWebsitesService_WaitForWebsiteStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebsitesService creates a new instance of MockWebsitesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebsitesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebsitesService {
	mock := &MockWebsitesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
